services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yml"]
    ports:
      - "4318:4318"
      - "4317:4317"
    environment:
      APP_ENV: dev
      LOG_LEVEL: info
    volumes:
      - ./observability/otel/collector-config.yml:/etc/otelcol/config.yml:ro

  leadmi:
    build: .
    container_name: leadmi
    depends_on:
      - otel-collector
    environment:
      SETTINGS_SKIP_DOTENV: "1"
      APP_ENV: dev
      ENABLE_OTEL: "true"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE: ${OPENAI_API_BASE:-https://api.openai.com}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REFRESH_TOKEN: ${GOOGLE_REFRESH_TOKEN}
      GOOGLE_TOKEN_URI: ${GOOGLE_TOKEN_URI:-https://oauth2.googleapis.com/token}
      GOOGLE_CALENDAR_ID: ${GOOGLE_CALENDAR_ID}
      HUBSPOT_ACCESS_TOKEN: ${HUBSPOT_ACCESS_TOKEN}
      HUBSPOT_API_BASE_URL: ${HUBSPOT_API_BASE_URL:-https://api.hubapi.com}
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
    volumes:
      - ./log_storage:/app/log_storage
    command: ["python", "main.py"]