receivers:
  otlp:
    protocols:
      http:
      grpc:

processors:
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 2s
  batch:
    send_batch_size: 512
    timeout: 5s
  resource:
    attributes:
      - action: upsert
        key: deployment.environment
        value: ${APP_ENV}

exporters:
  # Replace this with your real backend exporter later (e.g. otlp -> SaaS / Tempo / Jaeger)
  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [logging]

  telemetry:
    logs:
      level: info