# OpenTelemetry Collector Konfiguration
# Diese Version:
# - Aktiviert OTLP (HTTP + gRPC) auf allen Interfaces (0.0.0.0)
# - Setzt deployment.environment aus APP_ENV
# - Nutzt den debug Exporter zur Sichtprüfung der eingehenden Spans
# - Liefert interne Collector-Logs auf Level info
# Hinweis: debug Exporter NICHT in Produktion lassen – später z.B. durch otlp / jaeger / tempo / loki ersetzen.

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 2s
  batch:
    send_batch_size: 512
    timeout: 5s
  resource:
    attributes:
      - action: upsert
        key: deployment.environment
        value: ${APP_ENV}

exporters:
  debug:
    # basic: kompakte Ausgabe; detailed: sehr ausführlich
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [debug]

  telemetry:
    logs:
      level: info