name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  poller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Run Polling Trigger
        if: success() # nur wenn vorherige Schritte erfolgreich!
        env:
          CAL_LOOKAHEAD_DAYS: ${{ vars.CAL_LOOKAHEAD_DAYS }}
          CAL_LOOKBACK_DAYS: ${{ vars.CAL_LOOKBACK_DAYS }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          python -u polling/polling_trigger.py