name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      GOOGLE_TOKEN_URI: ${{ secrets.GOOGLE_TOKEN_URI }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Linting step
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      # Optional: Run tests
      - name: Run tests
        run: |
          pytest

      # Debug-Schritt: Überprüfe, ob die Google-Credentials gesetzt sind (optional, für Fehleranalyse)
      - name: Debug Google Credentials
        run: |
          echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
          echo "GOOGLE_CLIENT_SECRET length: ${#GOOGLE_CLIENT_SECRET}"
          echo "GOOGLE_REFRESH_TOKEN length: ${#GOOGLE_REFRESH_TOKEN}"
          echo "GOOGLE_TOKEN_URI=$GOOGLE_TOKEN_URI"
        shell: bash

      # Der neue Einstiegspunkt – nur falls gewünscht als Teil der CI:
      - name: Run main.py entrypoint
        run: python main.py