name: Polling Trigger Scheduled Run

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # Runs every day at 05:00 UTC

jobs:
  run-polling-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run polling trigger
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          CAL_LOOKAHEAD_DAYS: 14
          CAL_LOOKBACK_DAYS: 1
          TRIGGER_WORDS: "Demo,Test,Triggerword"
        run: |
          python -m polling.polling_trigger