name: Polling Trigger

on:
  schedule:
    - cron: '0 6-19 * * 1-5'  # Jede volle Stunde, Mo-Fr, 08–21 Uhr MESZ/MEZ (entspricht 06–19 Uhr UTC)
  workflow_dispatch:

jobs:
  poller:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Polling Trigger
      env:
        CAL_LOOKAHEAD_DAYS: ${{ vars.CAL_LOOKAHEAD_DAYS }}
        CAL_LOOKBACK_DAYS: ${{ vars.CAL_LOOKBACK_DAYS }}
      run: |
        python -u polling/polling_trigger.py