name: Polling Trigger

on:
  schedule:
    - cron: '*/5 * * * *'  # alle 5 Minuten
  workflow_dispatch:        # manueller Start im GitHub UI möglich

jobs:
  poller:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'   # oder eine andere, zu deinem Projekt passende Version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Polling Trigger
      run: |
        python -u polling/polling_trigger.py
